apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-api
  labels:
    k8s-app: rook-api
spec:
  jobLabel: rook-api
  selector:
    matchLabels:
      app: rook-api
      rook_cluster: rook
  namespaceSelector:
    matchNames:
    - rook
  endpoints:
  - port: rook-api
    interval: 30s
